# Generated by Django 3.0.6 on 2020-06-13 08:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('timestamp', models.DateTimeField(default=datetime.datetime(2020, 6, 13, 13, 53, 30, 624224))),
                ('content', models.TextField()),
            ],
        ),
    ]
