# Generated by Django 3.0.6 on 2020-06-15 17:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 15, 22, 33, 1, 131879)),
        ),
    ]
